spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: http://118.24.109.186:10080/wiki/config-rep
          username: wiki0@live.cn
          password: wiki2link
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8760
management:
  endpoints:
    web:
      exposure:
        include: "*"